language: node_js
node_js:
  - "4.1"

env:
  - VCR=playback

before_script:
  - npm install -g gulp
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - gulp tsd
  - gulp ts
  - gulp test
